export const Users = [
    {
        id:1,
        profilePicture:"assets/personne/1.jpg",
        username: "Safak Kocaoglu",
    },
    {
        id:2,
        profilePicture:"assets/personne/pp1.jpg",
        username: "Alexandra Shrum",
    },
    {
        id:3,
        profilePicture:"assets/personne/pp2.jpg",
        username: "Janell Durden",
    },
    {
        id:4,
        profilePicture:"assets/personne/pp4.jpg",
        username: "Dora Hawks",
    },
    {
        id:5,
        profilePicture:"assets/personne/pp5.jpg",
        username: "Thomas Holden",
    },
    {
        id:6,
        profilePicture:"assets/personne/pp6.jpg",
        username: "Shirley Beauchamp",
    },
    {
        id:7,
        profilePicture:"assets/personne/pp7.jpg",
        username: "Travis Bennet",
    },
    {
        id:8,
        profilePicture:"assets/personne/12.jpg",
        username: "Kristan Thomas",
    },
    {
        id:9,
        profilePicture:"assets/personne/pp8.jpg",
        username: "Gary Duty",
    },
    {
        id:10,
        profilePicture:"assets/personne/pp10.jpg",
        username: "Liam Benjamin",
    },
];

export const Posts = [
    {
        id:1,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/14.jpg",
        date:"5 mins ago",
        userId: 1,
        like:32,
        comment :9,
    },
    {
        id:2,
        photo:"assets/post/5.jpg",
        date:"15 mins ago",
        userId: 2,
        like:2,
        comment :1,
    },
    {
        id:3,
        desc:"Vitamine Sea.",
        photo:"assets/post/10.jpg",
        date:"1h  ago",
        userId: 3,
        like:41,
        comment :1,
    },
    {
        id:4,
        photo:"assets/post/16.jpg",
        date:"4h ago",
        userId: 4,
        like:15,
        comment :3,
    },
    {
        id:5,
        photo:"assets/post/8.jpg",
        date:"5h  ago",
        userId: 5,
        like:23,
        comment :5,
    },
    {
        id:6,
        photo:"assets/post/2.jpg",
        date:"7h  ago",
        userId: 6,
        like:18,
        comment :1,
    },
    {
        id:7,
        desc:"Nighty Street.",
        photo:"assets/post/11.jpg",
        date:"12h  ago",
        userId: 7,
        like:30,
        comment :5,
    },
    {
        id:8,
        photo:"assets/post/17.jpg",
        date:"20h ago",
        userId: 8,
        like:27,
        comment :7,
    },
    {
        id:9,
        photo:"assets/post/18.jpg",
        date:"1 day ago",
        userId: 9,
        like:14,
        comment :1,
    },
    {
        id:10,
        desc:"Love For My Cat.",
        photo:"assets/post/19.jpg",
        date:"2 days ago",
        userId: 10,
        like:18,
        comment :2,
    },
]
